### ISSUE TITLE
Daily Log File Rotation

### ISSUE THREAD

**Issue by Small6oy** [adonisjs/logger#37]
## Request Explained

I use adonisjs widely and the biggest issue is that we can't implement daily file logging without implementing custom code. It would be nice to implement it out of the box. 

In this regard I have added the updates I have managed to update the Aodnis Logger File.js library and have updated the app config changes to file, enabling easy file log rotation, by whatever period we wish to configure

## Solution
- Implementing winston-daily-rotate-file
- Updating App Log Configs

**Comment by thetutlage** [comment]
This module doesn't use Winston anymore and uses Pino. The docs for v5 will talk about log file rotation as well

**Comment by radiumrasheed** [comment]
@Small6oy do you mind sharing your snippet for daily rotating logs. That is if you have this done already. Cheers

**Comment by dionatanfmsilva** [comment]
I couldn't find a native mode so I added dynamic values to the filename in config/app.js

Maybe not the best way, but it works well.

`const Path = use('path')
const Moment = use('Moment')
`
...

` file: {
      driver: 'file',
      name: 'adonis-app',
      filename: Path.join('log', Moment().format('YYYY-MM-DD') + '-wapp-api.log'),
      level: 'info'
    }`

**Comment by dionatanfmsilva** [comment]
@radiumrasheed  after a long time I realized that this date is static of when the node process was started and not dynamic per day, I tried to do tests with an anonymous function, but without success.

**Comment by radiumrasheed** [comment]
oops, I actually didn't test this locally and went on to push for a client just today
Now I know I'm expecting a response, thanks for the heads up, will keep looking for ways

**Comment by diego-lipinski-de-castro** [comment]
so what was the solution for this afterall?

**Comment by Julien-R44** [comment]
https://github.com/pinojs/pino/blob/master/docs/help.md#log-rotation
Or if using PM2 : https://www.npmjs.com/package/pm2-logrotate
