### ISSUE TITLE
sprintf doesn't work

### ISSUE THREAD

**Issue by pdipasqua** [adonisjs/logger#39]
Hi, given that I use the default logger version in adonis, I find that it does not recognize the sprintf functionality.

Es: 
Logger.info("request is %j", {
  url: request.url(),
  controller: 'EventController'
})

returns Mar 17 11:20:22.257am info request is %j
without translate %j

**Comment by kauanmocelin** [comment]
Occurs same with me, but only when transport is type 'file'.

**Comment by thetutlage** [comment]
Sorry, A bit late to the party. But can you share the version of logger you are using. I just added a test case and seems to be working fine.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by adeel94mirza** [comment]
@thetutlage 
I am facing this issue.

**Console**
`info: serving app on http://127.0.0.1:3333
info: User Logged In: you@you.com`

**File**
`{"level":"info","message":"serving app on http://%s:%s"}
{"level":"info","message":"User Logged In: %s"}`

I can provide more info if needed.
