### ISSUE TITLE
error level warning, alert,crit,emerg Unknown 

### ISSUE THREAD

**Issue by pdipasqua** [adonisjs/logger#40]
Logger.emerg("Error Message", {
  url: request.url(),
  controller: 'EventController',
  method: 'store',
  params: params, //params se esite
  body: request.body,
  error:  e.message
})

[winston] Unknown logger level: warning
[winston] Unknown logger level: alert
[winston] Unknown logger level: crit
[winston] Unknown logger level: emerg

**Comment by thetutlage** [comment]
This repo is for v5 and not v4. I recommend opening the issue here https://github.com/adonisjs/adonis-framework
