### ISSUE TITLE
sprintf syntax does not work with file transport

### ISSUE THREAD

**Issue by adeel94mirza** [adonisjs/logger#45]
For some reason the sprintf syntax is not working with the file transport. It is fine for console transport

**Console**
`info: serving app on http://127.0.0.1:3333`
`info: User Logged In: you@you.com`

**File**
`info: serving app on %s%s`
`info: User Logged In: %s`

## Package version
4.1.0

## Node.js and npm version
node 12.12.0
npm 6.13.4

**Comment by ikenfin** [comment]
@adeel94mirza Same here!
But seems adding custom winston format to the config fixed issue:

```javascript
const winston = require('winston')

module.exports = {
  // ... config
  logger: {
    file: {
      driver: 'file',
      filename: 'app.log',
      level: 'info',
      // fix formats
      format: winston.format.combine(
        winston.format.splat(),
        winston.format.json()
      )
    }
  }
}
```
