### ISSUE TITLE
Server crashes when logging axios error

### ISSUE THREAD

**Issue by palfaro91** [adonisjs/logger#62]
### Package version

4.1.5

### Describe the bug

Logging an axios error causes the server to crash. Simple example 

```js
const url = `https://thisdomainshouldnotexist.co/some-slug`
try {
  await axios.put(url, { params; { someParam: 'data' } } ) /* this should fail */
} catch(e: any) {
  logger.error(e) /* THIS CAUSES THE SERVER TO CRASH */
}
```

### Reproduction repo

https://github.com/palfaro91/log-error

**Comment by thetutlage** [comment]
Hey, I see you reported the same issue with Pino as well. https://github.com/pinojs/pino/issues/1817

Yup, its true, AdonisJS v5 uses an older version of Pino and v6 will be using the latest upto-date version.

Lemme go through your code sample and see if I can help with some workaround for now.

**Comment by thetutlage** [comment]
The newer version of Logger uses latest version of Pino and hence it must not have any issues.

Regarding older versions, sorry, I was not able to have enough time to find a workaround

**Comment by palfaro91** [comment]
If I'm using Adonis v5, can I update Logger to the latest @thetutlage?

**Comment by RomainLanz** [comment]
No, the new version is only for AdonisJS 6.
