### ISSUE TITLE
Support falsy value in sprintf substitution in v6

### ISSUE THREAD

**Issue by gabor-s** [adonisjs/logger#66]
### Package version

6.0.1

### Describe the bug

This was fixed in [v4.1.6](https://github.com/adonisjs/logger/releases/tag/v4.1.6), but still exists in [v6.0.1](https://github.com/adonisjs/logger/blob/v6.0.1/src/logger.ts#L178).

**Comment by thetutlage** [comment]
Released. https://github.com/adonisjs/logger/releases/tag/v6.0.2
